language: node_js
node_js:
- node
- '4.3'
- iojs
- '0.12'
matrix:
  fast_finish: true
sudo: false
before_script:
- npm run typings
script:
- npm run ci
before_deploy:
- npm run build
deploy:
  provider: npm
  email: simon@simonemms.com
  api_key:
    secure: a8OxjTC5DAAOszzvZVEOloaoaguKD5N69C49OcBuTt6VmUJfYJYUgVrn6QFKnwt/ZWT029zuqYDiZOblJwri7Oa4/ew+Uh1TfX83pfnBosftMP92Dnc2+ccC8y9kIcKgqPKcQOR5dcvMmL75KoG2uNhxD9jqT4Mre7e45jStJRg=
  on:
    all_branches: true
    tags: true
    repo: riggerthegeek/steeplejack-http
