language: node_js
node_js:
- node
- '4.3'
- iojs
- '0.12'
matrix:
  fast_finish: true
sudo: false
script:
- npm run ci
before_deploy:
- npm run build
deploy:
  provider: npm
  email: simon@simonemms.com
  api_key:
    secure: YIuFSlbdqHrS7QNvMQfOvTFI8YSprLbugfzYVoPOTUFTg5V7c9YvW7oKarDxH5Q+Z2b5Pg7RYB4wH/dJfYQ4EnFSUrdyv09TYemFCzJQsJEBNbIfvTX91dxim++Upugydl4MTCKbMQPd/PbVtULLOZ2wPm+6YeFw0jdIKxIGQPFyPP1URrsJ6tC9UQx7qAKZYVNBTpvoMMVL5Y+mG56uNKtjCbj+rA1AyftkrWtUSNgJqVuEb0YPzUdrRGJS+1CDaaM6tU2qVhlJs2JLZaPU3iRixnJ0cTzA+ttLqdXl47hKsswDByTOq0OIG8own7ibHj9s+t79RuDpH9XDCiJG2JB6Ubk9PiSHmVTCA9beHOD3PF26lVTNhook56oU4B4pSPO1AySovgv27C4EYmCM7BnLXewfd5ETduLNvr4YF3fn6/fAe1XC+sLfKmOpVonIBElE5sb48lD91nxDiON+9FQEkbmyk+wrn7EKYeeUUIXD10eL63lxVkXMx26u++EVtuFktEPwPj+yUf5tx10x1R/c8XTpithQiw69Ge90QtAfC0ddr5R0s1lev54+E+3DPcQn6sR3ouvfv23S+kghUuf7n1BEX4aSrm0mO1+u7glgHAGYeFGCI72aqk6KopHOCx8jA4y269DcuQ6a4s4BEoq6e1Z5jzzMXOU/X+ZnM3Y=
  on:
    all_branches: true
    tags: true
    repo: riggerthegeek/steeplejack-http
