language: node_js
node_js:
- node
- '4.3'
- iojs
- '0.12'
matrix:
  fast_finish: true
sudo: false
before_script:
- npm run typings
script:
- npm run ci
before_deploy:
- npm run build
deploy:
  provider: npm
  email: simon@simonemms.com
  api_key:
    secure: m9iSna+jELqDJZKmvWvw9s9d8zkDUf9cOxDMtYFpHnMqKNe6IIX1Jc/mAbqEWGEuwp98OpGszihQVdfOXlvC/g6Q15Np0BCITD0ddiRgD3BjMYfqY0MmPSLfUQIC1M+5yMb/LQkOt1XIEY3xR6S9xq8AUajZTjzuKwgE72g+vUhN32sgE34buCBElkQ/K/fvnZJdkSLEZ6RvGsutFyYRaeVwm4FT6KWdHFHzPLDprB694VJo2KLNJIQa9YETOZ7FfLYYPYILaMDDQQi4wgyD+yrgRNiWJbJGMz2p4LBvAzYvaAxB5D5A34HRuOhswdUVoIvODVFjUsDhpNaD3spsct61phxEhGykrFhav6biTJCnNll19UCIfezrjtgV8wYTDo4cQZL6e+o7xtJ+kf7lpEs911+SCixLgH8a+cynXq07isOstK4xfKvwUQHKgBPZHACHcb5br8E2jSvNqaYhqeo6Kiw63aEwGgKf24Lr7y/aCq3/XrKKp1K2+lGknq4SgRGqy2K5ZP66+9VlDDfEAHVuGEMFue9+lfZ9WA9Ud4+cnnGAu70YEJuS9gERfK+BuztaHrjdtqHA9NRpZPWH/At9pZaCBNQ0rZBUMyzYfQnaw4evg2YG96mEXAhEz2BBn38STgV/RA1VZ+4cyReSRfnqtwAF1yyxC/Yh0T04GpY=
  on:
    all_branches: true
    tags: true
    repo: riggerthegeek/steeplejack-http
